# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SPCSDataScience',
                'doc_host': 'https://sfc-gh-jdemlow.github.io',
                'git_url': 'https://github.com/sfc-gh-jdemlow/SPCSDataScience',
                'lib_path': 'SPCSDataScience'},
  'syms': { 'SPCSDataScience.app': {},
            'SPCSDataScience.connection': { 'SPCSDataScience.connection.create_snowflake_session': ( 'connection.html#create_snowflake_session',
                                                                                                       'SPCSDataScience/connection.py'),
                                             'SPCSDataScience.connection.execute_sql_file': ( 'connection.html#execute_sql_file',
                                                                                               'SPCSDataScience/connection.py'),
                                             'SPCSDataScience.connection.get_connection_params': ( 'connection.html#get_connection_params',
                                                                                                    'SPCSDataScience/connection.py'),
                                             'SPCSDataScience.connection.load_credentials': ( 'connection.html#load_credentials',
                                                                                               'SPCSDataScience/connection.py'),
                                             'SPCSDataScience.connection.write_to_json': ( 'connection.html#write_to_json',
                                                                                            'SPCSDataScience/connection.py')}}}
