# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SPCSDataScience',
                'doc_host': 'https://sfc-gh-jdemlow.github.io',
                'git_url': 'https://github.com/sfc-gh-jdemlow/SPCSDataScience',
                'lib_path': 'DataScience'},
  'syms': { 'DataScience.app': {},
            'DataScience.connection': { 'DataScience.connection.create_snowflake_session': ( 'connection.html#create_snowflake_session',
                                                                                             'DataScience/connection.py'),
                                        'DataScience.connection.execute_sql_file': ( 'connection.html#execute_sql_file',
                                                                                     'DataScience/connection.py'),
                                        'DataScience.connection.get_connection_params': ( 'connection.html#get_connection_params',
                                                                                          'DataScience/connection.py'),
                                        'DataScience.connection.load_credentials': ( 'connection.html#load_credentials',
                                                                                     'DataScience/connection.py'),
                                        'DataScience.connection.write_to_json': ( 'connection.html#write_to_json',
                                                                                  'DataScience/connection.py')}}}
