-- These are useful queries to run to be able to check out your application

USE ROLE CONTAINER_USER_ROLE;
USE DATABASE CONTAINER_DEMO_DB;
USE SCHEMA PUBLIC;
USE WAREHOUSE CONTAINER_DEMO_WH;

SHOW SERVICES in account;

SHOW ENDPOINTS IN SERVICE MODELING_SNOWPARK_SERVICE;
CALL SYSTEM$REGISTRY_LIST_IMAGES('/CONTAINER_DEMO_DB/PUBLIC/IMAGE_REPO'); 
SHOW IMAGE REPOSITORIES;
CALL SYSTEM$GET_SERVICE_STATUS('CONTAINER_DEMO_DB.PUBLIC.MODELING_SNOWPARK_SERVICE');
CALL SYSTEM$GET_SERVICE_LOGS('CONTAINER_DEMO_DB.PUBLIC.MODELING_SNOWPARK_SERVICE', '0', 'executemodeling',10);

ALTER SERVICE CONTAINER_DEMO_DB.PUBLIC.MODELING_SNOWPARK_SERVICE SUSPEND;

USE ROLE ACCOUNTADMIN;
ALTER COMPUTE POOL CONTAINER_DEMO_POOL SUSPEND;
ALTER COMPUTE POOL CONTAINER_DEMO_POOL STOP ALL;
ALTER COMPUTE POOL CONTAINER_DEMO_POOL RESUME;

USE ROLE CONTAINER_USER_ROLE;

CREATE SERVICE CONTAINER_DEMO_DB.PUBLIC.MODELING_SNOWPARK_SERVICE
in compute pool CONTAINER_DEMO_POOL
from @specs
specification_file='modeling.yaml'
external_access_integrations = (ALLOW_ALL_EAI)
MIN_INSTANCES=1
MAX_INSTANCES=1
;

ALTER SERVICE CONTAINER_DEMO_DB.PUBLIC.MODELING_SNOWPARK_SERVICE RESUME;

CALL SYSTEM$GET_SERVICE_STATUS('CONTAINER_DEMO_DB.PUBLIC.MODELING_SNOWPARK_SERVICE');

-- DROP IMAGE REPOSITORY CONTAINER_DEMO_DB.PUBLIC.IMAGE_REPO; 