
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE CONTAINER_USER_ROLE;
-- GRANT CREATE SECRET ON SCHEMA CONTAINER_DEMO_DB.integrations TO ROLE CONTAINER_USER_ROLE;
USE ROLE CONTAINER_USER_ROLE;
CREATE OR REPLACE SECRET JDEMLOW_GH_SECRET
    TYPE = password
    USERNAME = 'sfc-gh-jdemlow'
    PASSWORD = '<in .env file>'
;
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE API INTEGRATION jdemlow_git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-jdemlow')
  ALLOWED_AUTHENTICATION_SECRETS = all
  ENABLED = TRUE;

-- DROP API INTEGRATION jdemlow_git_api_integration;
SHOW API INTEGRATIONS;
USE ROLE CONTAINER_USER_ROLE;

CREATE OR REPLACE GIT REPOSITORY JDEMLOW_STREAMLITEXAMPLE
    API_INTEGRATION = jdemlow_git_api_integration
    GIT_CREDENTIALS = JDEMLOW_GH_SECRET
    ORIGIN = 'https://github.com/sfc-gh-jdemlow/StreamlitExample'
;

ls @JDEMLOW_STREAMLITEXAMPLE/branches/igt_inference/;

ls @JDEMLOW_STREAMLITEXAMPLE/jupyter-nbs/;

alter git repository JDEMLOW_STREAMLITEXAMPLE fetch;

ls @VOLUMES/juypter-nbs/;

COPY FILES
  INTO @volumes/juypter-nbs/
  FROM @JDEMLOW_STREAMLITEXAMPLE/branches/igt_inference/
;

ls @VOLUMES/juypter-nbs/;