project:
  type: website

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
  title: "Snowpark Container Service For Data Science"
  sidebar:
    style: floating
  # sidebar:
  #   style: "docked"
  #   search: true
  #   collapse-level: 1
  #   tools: 
  #     - icon: github
  #       href: "https://github.com/sfc-gh-jdemlow/SPCSDataScience"
  #       aria-label: GitHub
  #   contents: 
  #     - href: index.ipynb
  #     - auto: FY24
  #     - auto: past_docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


# project:
#   type: website

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true

# website:
#   twitter-card: true
#   open-graph: true
#   repo-actions: [issue]
#   navbar:
#     background: primary
#     search: true
#   sidebar:
#     style: floating

metadata-files: [nbdev.yml, sidebar.yml]