# Built before this was released so keeping this for now until I update the action
# https://github.com/Snowflake-Labs/snowflake-cli-action
name: Deploy Snowpark CLI Execution

on:
  # Uncomment to enable on push
  # push:
  #   branches:
  #     - "*"
  #   tags:
  #     - "v*"
  workflow_dispatch:

jobs:

  snowcli:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

    steps:

    - uses: actions/checkout@v3

    - name: Install SnowCLI
      run: |
        pip install snowflake-cli-labs snow
        snow --version
        snow --help

    - name: Setup Snowflake config.toml
      id: SetupConfig
      run: |
        mkdir -p ~/.snowflake
        echo "[connections.myconnection]" > ~/.snowflake/config.toml
        echo "account = '${{ secrets.SNOWFLAKE_ACCOUNT }}'" >> ~/.snowflake/config.toml
        echo "user = '${{ secrets.SNOWFLAKE_USER }}'" >> ~/.snowflake/config.toml
        echo "password = '${{ secrets.SNOWFLAKE_PASSWORD }}'" >> ~/.snowflake/config.toml
        echo "database = '${{ secrets.SNOWFLAKE_DATABASE }}'" >> ~/.snowflake/config.toml
        echo "schema = '${{ secrets.SNOWFLAKE_SCHEMA }}'" >> ~/.snowflake/config.toml
        echo "warehouse = '${{ secrets.SNOWFLAKE_WAREHOUSE }}'" >> ~/.snowflake/config.toml
        echo "role = '${{ secrets.SNOWFLAKE_ROLE }}'" >> ~/.snowflake/config.toml
        echo "[cli.logs]" >> ~/.snowflake/config.toml
        echo "save_logs = true" >> ~/.snowflake/config.toml
        echo "level = 'info'" >> ~/.snowflake/config.toml
        echo "path = '/home/runner/.snowflake/logs'" >> ~/.snowflake/config.toml
        chmod 600 ~/.snowflake/config.toml
        mkdir -p /home/runner/.snowflake/logs

    - name: Testing snow cli connection
      id: TestSnowCLI
      run: |
        snow connection test -c "myconnection"
        snow connection set-default "myconnection"

    - name: Run Training
      id: train
      run: |
        snow sql -f ./DataScience/files/sql/05_execute_training.sql -v

    - name: Inference
      id: Inference
      run: |
        snow sql -f ./DataScience/files/sql/06_execute_inference.sql -v